api:
  paypal:
    mode: "sandbox"
    clientId: "PAYPAL_CLIENT_ID"
    clientSecret: "PAYPAL_CLIENT_SECRET"
  stripe:
    secretKey: "STRIPE_SECRET_KEY"
server:
  port: 8081
frontend:
  url: "http://localhost:3000/"
